import type { Metadata } from "next";

import { nunitoSans } from "@/fonts/index";

import { ThemeProvider } from "./components/theme-provider";
import "./globals.css";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      // TODO: For SEO and Accessibility, should change lang based on locale
      <html lang="en" suppressHydrationWarning>
         <body className={`${nunitoSans.variable} font-sans antialiased`}>
            <ThemeProvider
               attribute="class"
               defaultTheme="system"
               enableSystem
               disableTransitionOnChange
            >
               {children}
            </ThemeProvider>
         </body>
      </html>
   );
}
