import type { Metadata } from "next";

import { nunitoSans } from "@/fonts/index";

import "./globals.css";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      // TODO: For SEO and Accessibility, should change lang based on locale
      <html lang="en">
         <body className={`${nunitoSans.variable} font-sans antialiased`}>{children}</body>
      </html>
   );
}
