import type { Metadata } from "next";

import { getMessages } from "next-intl/server";

import { nunitoSans } from "@/fonts/index";
import { Locale } from "@/i18n/routing";
import Providers from "@/providers";

import { getUser } from "../../db/user";
import "../globals.css";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
   params,
}: Readonly<{
   children: React.ReactNode;
   params: Promise<{ locale: Locale }>;
}>) {
   const [{ locale }, messages, user] = await Promise.all([params, getMessages(), getUser()]);

   return (
      <html lang={locale} suppressHydrationWarning>
         <body
            className={`${nunitoSans.variable} flex h-screen min-h-screen w-full flex-col font-sans antialiased`}
         >
            <Providers messages={messages} user={user}>
               {/**TODO: Add terms and services dialog with a check on terms acceptance date to ensure acceptance of always the latest terms and privacy policy */}
               {children}
            </Providers>
         </body>
      </html>
   );
}
