import type { Metadata } from "next";

import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

import { UserStoreProvider } from "@/components/auth/user-store-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { nunitoSans } from "@/fonts/index";
import { Locale } from "@/i18n/routing";
import { ReactQueryProvider } from "@/lib/react-query";

import { getUser } from "../../db/user";
import "../globals.css";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
   params,
}: Readonly<{
   children: React.ReactNode;
   params: Promise<{ locale: Locale }>;
}>) {
   const [{ locale }, messages, user] = await Promise.all([params, getMessages(), getUser()]);

   return (
      <html lang={locale} suppressHydrationWarning>
         <body
            className={`${nunitoSans.variable} flex h-screen min-h-screen w-full flex-col font-sans antialiased`}
         >
            <NextIntlClientProvider messages={messages}>
               <ThemeProvider
                  attribute="class"
                  defaultTheme="system"
                  enableSystem
                  disableTransitionOnChange
               >
                  <UserStoreProvider user={user}>
                     <ReactQueryProvider>
                        <TooltipProvider>
                           <>
                              {/**TODO: Add terms and services dialog with a check on terms acceptance date to ensure acceptance of always the latest terms and privacy policy */}
                              {children}
                           </>
                        </TooltipProvider>
                     </ReactQueryProvider>
                  </UserStoreProvider>
               </ThemeProvider>
            </NextIntlClientProvider>
         </body>
      </html>
   );
}
