import type { Metadata } from "next";

import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

import { UserStoreProvider } from "@/components/auth/user-store-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { nunitoSans } from "@/fonts/index";
import { ReactQueryProvider } from "@/lib/react-query";

import { getUser } from "../db/user";
import "../globals.css";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   const [messages, user] = await Promise.all([getMessages(), getUser()]);

   return (
      // TODO: For SEO and Accessibility, should change lang based on locale
      <html lang="en" suppressHydrationWarning>
         <body className={`${nunitoSans.variable} font-sans antialiased`}>
            <NextIntlClientProvider messages={messages}>
               <ThemeProvider
                  attribute="class"
                  defaultTheme="system"
                  enableSystem
                  disableTransitionOnChange
               >
                  <UserStoreProvider user={user}>
                     <ReactQueryProvider>{children}</ReactQueryProvider>
                  </UserStoreProvider>
               </ThemeProvider>
            </NextIntlClientProvider>
         </body>
      </html>
   );
}
